### ISSUE TITLE
github有多段拍摄的代码

### ISSUE THREAD

**Issue by 986138497** [ZZZZou/AwemeLike#1]

**Comment by 986138497** [comment]
1

**Comment by ZZZZou** [comment]
最近没时间额，如果你有兴趣，可以提个pr过来。。

**Comment by 986138497** [comment]
好的,我参考了别人的 app ,    https://github.com/lmf12/SimpleCam 下载 0.30 版本有 opencv 人脸特征点识别,   https://github.com/biyuhuaping/GPUImageDemo这个有多段录制
